apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.fullnameOverride }}-service
  labels:
    app: {{ .Values.api.nameOverride }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: {{ .Values.api.service.protocol }}
      name: {{ .Values.api.service.name }}
  selector:
    app: {{ .Values.api.nameOverride }}