apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../namespaces/flux-system.yaml
  - ../namespaces/staging.yaml
  - ../namespaces/prod.yaml
  - ../sources/helm-repositories.yaml
  - ../sources/git-repository.yaml
