apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-staging
  namespace: staging
spec:
  kubernetesConfig:
    kubernetesClusterDomain: cluster.local
  redisExporter:
    enabled: false
  redisConfig:
    additionalRedisConfig: "maxmemory 100mb\nmaxmemory-policy allkeys-lru"
  nodeSelector:
    env: staging