apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-client
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
 chart: client
      sourceRef:
    kind: GitRepository
        name: weather-app
        namespace: flux-system
   sourceRef:
        path: .helm/client
  valuesFrom:
    - kind: ConfigMap
      name: weather-client-values
  suspend: false
