apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - configmap-client-values.yaml
  - configmap-api-values.yaml
  - redis.yaml
  - client-release.yaml
  - api-release.yaml
